### PR TITLE
Updated to newest tree sitter

### PR DESCRIPTION
**Pull request by Baael**
Updated tree sitter submodule. 
Added column and row properties to ASTNode, it is helpful when matching indentations.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for this; great work! And thanks for taking the time to update my broken README example!

I made small adjustments to the API in addition to your patch:
 * Instead of having `row` and `column` properties, nodes now have `startPosition` and `endPosition` properties that return `{row, column}` objects.
 * The `start` and `end` properties are now called `startIndex` and `endIndex`, to distinguish them from `startPosition` and `endPosition`.

**Comment by Baael** [comment]
Perfect! Thank you :) I wanted to expose TSPoint as JS object but your changes already solved that.

**Comment by maxbrunsfeld** [comment]
@Baael Great! Out of curiosity, how did you come across this project? Are you using it?

**Comment by Baael** [comment]
I was googling for lexer, parser and grammar for nodejs. After trying few projects I've found tree-sitter simplest in writing and very clear. I love idea that it can be compiled to C.

I am using it in my own project for IoT, it includes: testing/scripting pseudo code and checking syntax in realtime.

For fun I've started to writing my own coffeescript parser :) So now I am trying to understand how to add and handle rules in tree-sitter, like "indentation". 

For me your project is perfect :) I love it.

**Comment by maxbrunsfeld** [comment]
Great! Adding indentation support to tree-sitter is the next big improvement that I plan to do. [This paper](http://soft-dev.org/pubs/html/diekmann_tratt__eco_a_language_composition_editor/) describes how @ptersilie and @ltratt implemented an indentation-sensitive incremental parser in their [eco](https://github.com/softdevteam/eco) editor. I think they have some useful insights.

I'm very interested in anything you come up with regarding indentation-sensitive parsing.

**Comment by Baael** [comment]
I think I cannot add any serious value in this area. More I dig into code, more I understand that I do not understand it, and saturday evening at home isn't helping :)
It will take more time for me to get into that, but for sure it is worthy.


But I will share my initial idea:

We have informations about token start position (so I think accept token state can access it too):

```
{ '0': 'start_token',
  '1': { chars: '26', rows: '1', columns: '2' },
  '2': 'lex' }
```

then we can add new rule, for example called "nested", it may look like that in the grammar file:

```

indentation: -> [/\s{2}/, /\t/ ] # basic unit, may be multiplied

rules:
  
  function: ->
    seq '->', nested repeat @expression
```

What it does is adding criteria to children rules:

(in some pseudocode)

```
nested rule =
  if left rule start_token columns < right rule start_token columns
    continue with right rule
  else
    break - it is end of nested, nested lines are not found or EOF
```

where left rule is rule before 'nested' and right rule is rule inside.
But I still have no idea if it is possible to access to such informations.

It solves two situations, similar to coffeescript, first:

```
firstBlock = -> 
  @doSomething

anotherBlock = 1
```

second:

```
firstBlock = -> var_a: 1,
  var_b: 2
  var_c:
    { var_d: 3, var_e: 4 }

anotherBlock = 1
```

There can be some problems too, like:

```
fn = ->
  console.log """

text without indentation

  """
```

But I think it can be solved with precendence adjusting of rule for multiline strings. 
Thank you for link, I really need to get more knowledge about all parsing algorithms.

**Comment by ltratt** [comment]
@maxbrunsfeld: Lukas has created an updated indentation algorithm that plays better with multi-line strings and so on (which the SLE paper, like the work it's based on, pretty much ignored). It's difficult to put a timeline on when that'll be fully written up, but we'd be happy to share a draft when it's ready. The new algorithm is already in [Eco](http://github.com/softdevteam/eco), although i appreciate that extracting the core ideas from a big lump of code is not exactly trivial.

**Comment by maxbrunsfeld** [comment]
Thanks @ltratt; I'll have a look at eco's new approach when I start working on indentation support.

**Comment by ltratt** [comment]
@maxbrunsfeld Please feel free to give us a ping when you get to that point. We're always happy to chat with users of this stuff!

**Pull request merged**
